server:
  port: 9096

spring:
  application:
    name: visa-service

  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:h2:mem:visa_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${POSTGRES_USERNAME:sa}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name:
      - org.postgresql.Driver
      - org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: ${POSTGRES_DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        dialect:
          - org.hibernate.dialect.PostgreSQLDialect
          - org.hibernate.dialect.H2Dialect


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  topic:
    visa-events: visa-events

logging:
  level:
    root: info
    org.springframework.kafka: info
