server:
  port: 9097

spring:
  application:
    name: oauth-service

  datasource:
    url: ${AUTH_DB_URL:jdbc:h2:mem:auth_db;DB_CLOSE_DELAY=-1;MODE=MySQL}
    username: ${AUTH_DB_USER:sa}
    password: ${AUTH_DB_PASS:}
    driver-class-name:
     - com.mysql.cj.jdbc.Driver
     - org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: ${POSTGRES_DDL_AUTO:create-drop}
    properties:
      hibernate:
        dialect:
          - org.hibernate.dialect.MySQLDialect
          - org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

jwt:
  secret: ${JWT_SECRET:flpZVEZrUG1ORD01Y2MxInkyP2oiQFFqeTN0TXk4NTk=}
  expiration-time: 36000000
  refresh-expiration-time: 86400000

logging:
  level:
    root: info
    org.springframework.security: info
