server:
  port: 9095

spring:
  application:
    name: extend-residence-permit-service

  datasource:
    url: ${REGISTRATION_POSTGRES_URL:jdbc:postgresql://localhost:5432/registration_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  topic:
    visa-events: visa-events
    passport-events: passport-events
    residence-permit-events: residence-permit-events
    identification-cart-events: identification-cart-events

logging:
  level:
    root: info
    org.springframework.kafka: info
